# Generated by Django 4.2.1 on 2023-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_company_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finished_at',
            field=models.DateField(null=True),
        ),
    ]
